# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DietRecord' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DietRecord
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'FirebaseFirestoreSwift'
pod 'Charts'
pod 'SwiftLint'
pod 'Kingfisher'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Storage'
pod 'JGProgressHUD'
pod 'Firebase/Auth'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      target.build_settings(configuration.name)['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end